[project]
name = "misis2026s-23-03-feygenberg-m-i"
version = "0.1.0"
description = "CT Walnut scan segmentation and 3D vectorization"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pyglet<2",
    "pynrrd>=1.1.3",
    "scikit-image>=0.26.0",
    "scipy>=1.17.1",
    "tifffile>=2026.5.2",
    "trimesh>=4.12.2",
]

[tool.setuptools.packages.find]
include = ["lab*"]